=== BauhausLuftfahrt/PAXelerate/cpacs_schema/toolspecific.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="paxelerate" xmlns="paxelerate"
            elementFormDefault="qualified">


    <!-- Global element -->
    <xsd:element name="content" type="paxelerateType"/>

    <!-- Type of the global tool element -->
    <xsd:complexType name="paxelerateType">
        <xsd:sequence>
            <xsd:element name="input" type="paxelerateInputType"/>
            <xsd:element name="output" type="paxelerateOutputType" minOccurs="0"/>
            <xsd:element name="settings" type="paxelerateSettingsType"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="paxelerateInputType">
        <xsd:sequence>
            <xsd:element name="studies" type="studiesType"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="studiesType">
        <xsd:sequence>
            <xsd:element name="study" type="studyType" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="studyType">
        <xsd:sequence>
            <xsd:element name="loadFactor" type="xsd:double"/>
            <xsd:element name="activeDoorUIDs" type="xsd:string"/>
            <xsd:element name="iterations" type="xsd:int"/>
            <xsd:element name="simulationType">
                <xsd:simpleType>
                    <xsd:restriction
                            base="xsd:string">
                        <xsd:enumeration value="BOARDING"/>
                        <xsd:enumeration value="DEBOARDING"/>
                        <xsd:enumeration value="EMERGENCY"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="seatType">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="DEFAULT"/>
                        <xsd:enumeration value="SIDEWAYS_FOLDABLE"/>
                        <xsd:enumeration value="LIFTING_SEAT_PAN"/>
                        <xsd:enumeration value="BRING_YOUR_OWN"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="simulationGridResolution" type="xsd:double"/>
            <xsd:element name="simulationSpeedFactor" type="xsd:double"/>
            <xsd:element name="passengerSortingScheme">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="RANDOM"/>
                        <xsd:enumeration value="RTF"/>
                        <xsd:enumeration value="FTR"/>
                        <xsd:enumeration value="WTA"/>
                        <xsd:enumeration value="WTA_RTF"/>
                        <xsd:enumeration value="WTA_FTR"/>
                        <xsd:enumeration value="BLOCK"/>
                        <xsd:enumeration value="BOARDING_CLASS_RANDOM"/>
                        <xsd:enumeration value="STEFFEN"/>
                        <xsd:enumeration value="MILNE_KELLY"/>
                        <xsd:enumeration value="BIG_BAGS_AFT"/>
                        <xsd:enumeration value="BIG_BAGS_FRONT"/>
                        <xsd:enumeration value="MAX_BAGS_AFT"/>
                        <xsd:enumeration value="MAX_BAGS_FRONT"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="doorSelection">
                <xsd:simpleType>
                    <xsd:restriction
                            base="xsd:string">
                        <xsd:enumeration value="CLOSEST"/>
                        <xsd:enumeration value="CLOSEST_BEHIND"/>
                        <xsd:enumeration value="CLOSEST_FRONT"/>
                        <xsd:enumeration value="RANDOM"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="percentageOfPassengersWithJackets" type="xsd:double"/>
            <xsd:element name="percentageOfPassengersWithSmallBags" type="xsd:double"/>
            <xsd:element name="percentageOfPassengersWithMediumBags" type="xsd:double"/>
            <xsd:element name="percentageOfPassengersWithLargeBags" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="uID" type="xsd:ID" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="paxelerateSettingsType">
        <xsd:sequence>
            <xsd:element name="displaySimulation" type="xsd:boolean"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="paxelerateOutputType">
        <xsd:sequence>
            <xsd:element name="studiesOutput" type="studiesOutputType"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="studiesOutputType">
        <xsd:sequence>
            <xsd:element name="studyOutput" type="studyOutputType" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="studyOutputType">
        <xsd:sequence>
            <xsd:element name="averageBoardingTime" type="xsd:double"/>
            <xsd:element name="studyIterationsOutput" type="studyIterationsOutputType"/>
        </xsd:sequence>
        <xsd:attribute name="linkedStudyUID" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="studyIterationsOutputType">
        <xsd:sequence>
            <xsd:element name="studyIterationOutput" type="studyIterationOutputType" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="studyIterationOutputType">
        <xsd:sequence>
            <xsd:element name="boardingTime" type="xsd:double"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== BauhausLuftfahrt/PAXelerate/cpacs_schema/toolspecific.xml
<?xml version="1.0" encoding="UTF-8"?>
<content xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="paxelerate toolspecific.xsd" xmlns="paxelerate">
    <input>
        <studies>
            <study uID="study_name">
                <loadFactor>1.0</loadFactor>
                <activeDoorUIDs>door_id_1;door_id_2</activeDoorUIDs>
                <iterations>1</iterations>
                <simulationType>BOARDING</simulationType>
                <displaySimulation>true</displaySimulation>
                <seatType>DEFAULT</seatType>
                <simulationGridResolution>0.1</simulationGridResolution>
                <simulationSpeedFactor>1</simulationSpeedFactor>
                <passengerSortingScheme>RANDOM</passengerSortingScheme>
                <doorSelection>CLOSEST</doorSelection>
                <percentageOfPassengersWithJackets>25</percentageOfPassengersWithJackets>
                <percentageOfPassengersWithSmallBags>25</percentageOfPassengersWithSmallBags>
                <percentageOfPassengersWithMediumBags>25</percentageOfPassengersWithMediumBags>
                <percentageOfPassengersWithLargeBags>25</percentageOfPassengersWithLargeBags>
            </study>
        </studies>
    </input>
</content>
